#!/usr/bin/env bash
# install.sh — MeshTTY installer
#
# Supports:
#   - Raspberry Pi OS (Lite or Desktop)
#   - Ubuntu 22.04 / 24.04 (and derivatives: Mint, Pop!_OS, etc.)
#
# Both platforms are Debian-based so the same apt-get commands apply.
#
# Usage:
#   bash install.sh
#
# Run as your normal user (not root). sudo is invoked only where needed.
#
# After installation, use the generated start script to launch the app:
#   ./meshtty.sh          # from this directory, or
#   ~/meshtty.sh          # if you chose to copy it to your home dir
#
# On Raspberry Pi only: you may also opt in to auto-launch on tty1
# (the physical screen), so the app starts automatically on boot login.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$HOME/.venv/meshtty"
START_SCRIPT="$SCRIPT_DIR/meshtty.sh"

# ------------------------------------------------------------------ #
# Detect platform                                                      #
# ------------------------------------------------------------------ #
IS_PI=false
if grep -qi "raspberry" /proc/device-tree/model 2>/dev/null \
   || grep -qi "raspbian\|raspberry" /etc/os-release 2>/dev/null; then
    IS_PI=true
fi

if $IS_PI; then
    PLATFORM="Raspberry Pi"
else
    PLATFORM="Ubuntu / Debian"
fi

echo "=== MeshTTY Installer ==="
echo ">>> Detected platform: $PLATFORM"
echo ""

# ------------------------------------------------------------------ #
# 1. System dependencies                                               #
# ------------------------------------------------------------------ #
echo ">>> Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y \
    python3-pip \
    python3-venv \
    libglib2.0-dev \
    bluetooth \
    libbluetooth-dev \
    bluez

# Ensure the Bluetooth service is running (important on Ubuntu where
# it may not start automatically after install)
sudo systemctl enable bluetooth --quiet 2>/dev/null || true
sudo systemctl start  bluetooth         2>/dev/null || true

# ------------------------------------------------------------------ #
# 2. Python virtual environment                                        #
# ------------------------------------------------------------------ #
echo ">>> Creating virtualenv at $VENV_DIR..."
python3 -m venv "$VENV_DIR"
source "$VENV_DIR/bin/activate"

# ------------------------------------------------------------------ #
# 3. Install Python packages                                           #
# ------------------------------------------------------------------ #
echo ">>> Installing Python dependencies..."
pip install --upgrade pip --quiet
pip install -r "$SCRIPT_DIR/requirements.txt" --quiet
pip install -e "$SCRIPT_DIR" --quiet

# ------------------------------------------------------------------ #
# 4. Verify meshtastic installation                                    #
# ------------------------------------------------------------------ #
echo ">>> Verifying meshtastic Python library..."
if python -c "import meshtastic" 2>/dev/null; then
    MESH_VER=$(python -c "import meshtastic; print(meshtastic.__version__)" 2>/dev/null || echo "unknown")
    echo "    OK: meshtastic $MESH_VER"
else
    echo ""
    echo "ERROR: The meshtastic Python library did not install correctly."
    echo "Check the pip output above for errors, then re-run install.sh."
    exit 1
fi

echo ">>> Verifying meshtastic CLI command..."
if command -v meshtastic >/dev/null 2>&1; then
    echo "    OK: $(command -v meshtastic)"
else
    echo ""
    echo "ERROR: The meshtastic CLI command was not found in the virtualenv."
    echo "Try running: pip install --force-reinstall meshtastic"
    exit 1
fi

# ------------------------------------------------------------------ #
# 5. Serial port access                                               #
# ------------------------------------------------------------------ #
echo ">>> Adding $USER to dialout group (serial/USB radio access)..."
sudo usermod -aG dialout "$USER"

# ------------------------------------------------------------------ #
# 6. Bluetooth access                                                  #
# ------------------------------------------------------------------ #
echo ">>> Adding $USER to bluetooth group..."
sudo usermod -aG bluetooth "$USER"

# ------------------------------------------------------------------ #
# 7. Generate start script                                             #
# ------------------------------------------------------------------ #
echo ">>> Generating start script at $START_SCRIPT..."
cat > "$START_SCRIPT" << STARTSCRIPT
#!/usr/bin/env bash
# meshtty.sh — launch MeshTTY
# Works on Raspberry Pi OS and Ubuntu.
# Generated by install.sh — safe to re-run install.sh to regenerate.

VENV="$VENV_DIR"
APP_DIR="$SCRIPT_DIR"

if [[ ! -f "\$VENV/bin/activate" ]]; then
    echo "ERROR: virtualenv not found at \$VENV"
    echo "Please re-run install.sh"
    exit 1
fi

source "\$VENV/bin/activate"
cd "\$APP_DIR"
exec python -m meshtty.main "\$@"
STARTSCRIPT
chmod +x "$START_SCRIPT"
echo ">>> Start script created: $START_SCRIPT"

# ------------------------------------------------------------------ #
# 8. Pi-only: optional auto-launch on tty1                            #
# ------------------------------------------------------------------ #
if $IS_PI; then
    echo ""
    echo ">>> Raspberry Pi detected."
    read -r -p ">>> Auto-launch MeshTTY on tty1 login (physical screen)? [y/N] " answer
    if [[ "${answer,,}" == "y" ]]; then
        BASHRC="$HOME/.bashrc"
        LAUNCH_BLOCK="
# MeshTTY auto-launch on tty1 (physical Pi screen)
if [[ \"\$(tty)\" == \"/dev/tty1\" ]]; then
    exec $START_SCRIPT
fi"
        if ! grep -q "meshtty auto-launch" "$BASHRC"; then
            echo "$LAUNCH_BLOCK" >> "$BASHRC"
            echo ">>> Added auto-launch block to $BASHRC"
        else
            echo ">>> Auto-launch already present in $BASHRC, skipping."
        fi
    fi
fi

# ------------------------------------------------------------------ #
# Done                                                                 #
# ------------------------------------------------------------------ #
echo ""
echo "=== Installation complete ==="
echo ""
echo "IMPORTANT: Log out and back in for group membership to take effect."
echo "(This is required for serial port and Bluetooth access.)"
echo ""
echo "To test your radio connection before launching MeshTTY:"
echo "  source $VENV_DIR/bin/activate"
echo "  meshtastic --port /dev/ttyUSB0 --info   # adjust port as needed"
echo "  deactivate"
echo ""
echo "To launch MeshTTY:"
echo "  $START_SCRIPT"
echo ""
if ! $IS_PI; then
    echo "Ubuntu notes:"
    echo "  - Run in any terminal emulator (GNOME Terminal, Konsole, Kitty, etc.)"
    echo "  - SSH sessions are also fully supported"
    echo "  - If Bluetooth fails, check: sudo systemctl status bluetooth"
    echo ""
fi
echo "Logs are written to: /tmp/meshtty.log"
