#!/usr/bin/env bash
# meshtty.sh — launch MeshTTY
# Works on Raspberry Pi OS and Ubuntu.
# Generated by install.sh — safe to re-run install.sh to regenerate.

VENV="/home/kendel/.venv/meshtty"
APP_DIR="/home/kendel/Vibe/MeshTTY"

# Require an interactive terminal — Textual cannot run without one
if ! [[ -t 0 && -t 1 ]]; then
    echo "ERROR: MeshTTY requires an interactive terminal (stdin/stdout must be a TTY)." >&2
    exit 1
fi

# Ensure a capable TERM for Textual rendering
if [[ "$TERM" == "dumb" || -z "$TERM" ]]; then
    export TERM=xterm-256color
fi

if [[ ! -f "$VENV/bin/activate" ]]; then
    echo "ERROR: virtualenv not found at $VENV"
    echo "Please re-run install.sh"
    exit 1
fi

source "$VENV/bin/activate"
cd "$APP_DIR"

# At boot, wait up to 10 s for a USB serial device to enumerate if serial
# is the configured transport.  Harmless no-op once the device is present.
CONFIG="$HOME/.config/meshtty/config.json"
if grep -q '"default_transport".*"serial"' "$CONFIG" 2>/dev/null; then
    if ! ls /dev/ttyUSB* /dev/ttyACM* >/dev/null 2>&1; then
        echo "Waiting for USB serial device..."
        for _i in $(seq 1 10); do
            ls /dev/ttyUSB* /dev/ttyACM* >/dev/null 2>&1 && break
            sleep 1
        done
    fi
fi

exec python -m meshtty.main "$@"
