#!/usr/bin/env bash
# meshtty.sh — launch MeshTTY
# Works on Raspberry Pi OS and Ubuntu.
# Generated by install.sh — safe to re-run install.sh to regenerate.

VENV="/home/kendel/.venv/meshtty"
APP_DIR="/home/kendel/Vibe/MeshTTY"

if [[ ! -f "$VENV/bin/activate" ]]; then
    echo "ERROR: virtualenv not found at $VENV"
    echo "Please re-run install.sh"
    exit 1
fi

source "$VENV/bin/activate"
cd "$APP_DIR"
exec python -m meshtty.main "$@"
